### ISSUE TITLE
`window.hmrState` is 1 step behind the actual state

### ISSUE THREAD

**Issue by MichaelBergquistSuarez** [andyrj/hyperapp-webpack-hmr#4]
If I trigger an action twice, the state is always one step behind the last state.

I have a counter;
```js
const actions = {
  up: value => state => ({ count: state.count + value })
};

hmrApp(window._state, actions, view, document.body);

if (module.hot) {
   module.hot.accept('../shared/view.js', () => {
    hmrApp(window.hmrState, actions, require('../shared/view'), document.body)
  })
}
```

If I trigger `up` twice, the counter will have increased the state by 2. But when I change a file that trigger a webpack reload, the state will returned to as it was when it had increased by 1

**Comment by andyrj** [comment]
Going to look into this, I think I broke this when I changed from 0.13 to 1.0.x hyperapp api...  I can probably reuse some of the code in my hyperapp-redux-devtools to correct this.

**Comment by andyrj** [comment]
Looking at all of this again I'm not sure it's even worth having this library now with the changes to hyperapp API returning actions I think all you need for webpack-hmr is:
```js
/* myApp.js */
var { h, app } = require('hyperapp')
module.exports = function myApp(initState) {
  return app(
    initState,
    {
      getState: () => state => state,
      increment: () => state => ({ count: state.count + 1 }),
      decrement: () => state => ({ count: state.count - 1})
    },
    (state) => h("div", {}, count)
  );
}
```
```js
/* index.js */
var myApp = require('./myApp')

var appActions = myApp({ count: 0 })

if (module.hot) {
  module.hot.accept('./myApp', function(){
    appActions = myApp(appActions.getState());
  })
}
```

**Comment by andyrj** [comment]
closing this repo as the library is no longer needed, npm package has been deprecated.  Please refer to the readme for example usage of hyperapp with webpack hmr.
